server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5433/auditoria_db?options=-c%20TimeZone=UTC
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

jwt.secret=miClaveSecretaSuperSeguraParaJWT2026!QueDebeSerLarga
jwt.expiration=86400000

python.service.url=http://localhost:8000

logging.level.org.springframework.security=DEBUG
logging.level.com.zaxxer.hikari=DEBUG